source 'https://rubygems.org'
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem 'jekyll', '~> 3.9.2'
gem 'webrick'

group :jekyll_plugins do
    gem 'jekyll-default-layout', '~> 0.1.4'
    gem 'jekyll-optional-front-matter', '~> 0.3.2'
    gem 'jekyll-readme-index', '~> 0.3.0'
    gem 'jekyll-seo-tag', '~> 2.8'
    gem 'jekyll-file-size', '~> 0.0.7'
    gem 'kramdown-parser-gfm', '~> 1.1'
end
